@startuml

!include ../style.puml
title Adding a Preset to the Packing List

start

:Receives an ""addpreset"" command;

if () then ([valid command])

    if () then ([trip has been set])

            :Parses the
            ""addpreset"" command
            and the category
            to be added;

            if () then ([valid category])

                :Retrieves the list
                of items from the
                system;

                :Adds all the items
                into the packing list;

                :Shows a success
                message;

            else ([else])

                :Shows an invalid
                category error
                message;

            endif


    else ([else])
            :Shows
            a trip-not-set
            error message;
    endif

else ([else])

    :Shows an
    invalid command
    error message;
endif

stop

@enduml
