@startuml
!include ../style.puml

title Overlap check between 2\n accommodation bookings

start

:Gets the start day and end day of
""AccommodationBooking"" 1;

:Gets the start day and end day of
""AccommodationBooking"" 2;

:Calculates the total duration
of both bookings;

:Gets latest end day of among
the 2 bookings;

:Gets earliest start day of among
the 2 bookings;

:Calculates the acceptable duration;

note right
acceptable duration =
latest end day - earliest start day
end note

if () then ([total duration\n is within the \n acceptable\n duration])

    :Continues the check
    for the next
    ""AccommodationBooking"";

else ([else])

    :Stops the check and
    shows an error message;

endif

stop
@enduml
