@startuml
!include ../style.puml
title Automatic Scheduling of a Transport Booking

start

:Receives an ""addtransport"" command;

if () then ([valid command])

    if () then ([trip has been set])

        :Parses the ""addtransport""
        command and the user
        specified transport booking;

        :Creates a corresponding
        ""DayScheduleEntry"" using
        this transport booking;

        :Calculates the day to
        schedule this transport
        booking;

        if () then ([valid day])

            :Adds the
            ""DayScheduleEntry""
            into the schedule;

            :Adds the transport
            booking into the
            ""TransportBookingManager"";

        else ([else])
            :Shows an invalid
            date and time error
            message;

        endif

    else ([else])

    :Shows a
    trip-not-set
    error message;

    endif

else ([else])
    :Shows an invalid
    command error
    message;

endif

stop

@enduml
