@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant "**:LogicManager**" as LogicManager LOGIC_COLOR
participant "**:EasyTravelParser**" as EtParser LOGIC_COLOR
participant "**:AddActivityCommandParser**" as AddActivityCommandParser LOGIC_COLOR
participant "**:AddActivityCommand**" as AddActivityCommand LOGIC_COLOR
end box

[-> LogicManager : execute("addactivity title/Osaka Castle View \n duration/1 \n location/Osaka")
activate LogicManager

LogicManager -> EtParser : parseCommand("addactivity title/Osaka Castle View \n duration/1 \n location/Osaka")
activate EtParser

create AddActivityCommandParser
EtParser -> AddActivityCommandParser
activate AddActivityCommandParser

AddActivityCommandParser --> EtParser
deactivate AddActivityCommandParser

EtParser -> AddActivityCommandParser : parse("addactivity title/Osaka Castle View \n duration/1 \n location/Osaka")
activate AddActivityCommandParser

create AddActivityCommand
AddActivityCommandParser -> AddActivityCommand
activate AddActivityCommand

AddActivityCommand --> AddActivityCommandParser
deactivate AddActivityCommand

AddActivityCommandParser --> EtParser
deactivate AddActivityCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddActivityCommandParser -[hidden]-> EtParser
destroy AddActivityCommandParser

EtParser --> LogicManager
deactivate EtParser

LogicManager -> AddActivityCommand : execute()
activate AddActivityCommand

ref over AddActivityCommand : Add activity

AddActivityCommand --> LogicManager : result
deactivate AddActivityCommand

[<--LogicManager
deactivate LogicManager
@enduml

