@startuml
!include ../style.puml

Class Logic <<Interface>> LOGIC_COLOR_T1 {
+ execute()
}

Class LogicManager LOGIC_COLOR_T1 {
+ execute()
}

Class TransportBooking MODEL_COLOR_T1 {
- mode : Mode
- startLocation : Location
- endLocation : Location
- startDateTime DateTime
- endDateTime DateTime
+ areLocationsValid(Location, Location) : boolean
+ isTimeValid(DateTime) : boolean
}

Class Model <<Interface>> MODEL_COLOR_T1 {
+ addTransportBooking()
+ scheduleTransport(TransportBooking)
+ unscheduleTransport(DayScheduleEntry)
}

Class ModelManager MODEL_COLOR_T1 {
+ addTransportBooking()
+ scheduleTransport(TransportBooking)
+ unscheduleTransport(DayScheduleEntry)
}

Class TransportBookingManager MODEL_COLOR_T1 {
+ addTransportBooking()
}

Class TripManager MODEL_COLOR_T1 {
+ scheduleTransport(TransportBooking)
+ unscheduleTransport(DayScheduleEntry)
}

Class DaySchedule MODEL_COLOR_T1 {
+ addSchedule(DayScheduleEntry)
+ removeScheduleEntry(DayScheduleEntry)
}

Class DayScheduleEntry MODEL_COLOR_T1 {
- type : Type
- title : Title
- startDateTime : DateTime
- endDateTime : DateTime
- durationInHours : long
- location : Location
}

LogicManager .up-|> Logic
LogicManager -left-> Model

ModelManager .up-|> Model

ModelManager -right-> TripManager
TripManager -right-> " * " DaySchedule
DaySchedule -down-> " * " DayScheduleEntry

ModelManager -down-> TransportBookingManager
TransportBookingManager -right-> " * " TransportBooking

@enduml
