@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
Interface ReadOnlyXYZ <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class XYZManager
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

}


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

XYZManager .up.|> ReadOnlyXYZ

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "6" XYZManager
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

@enduml
