@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
Interface ReadOnlyXYZ <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class DukeCooks
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package BlackBox {
}

}


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

DukeCooks .up.|> ReadOnlyXYZ

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" DukeCooks
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

DukeCooks *--> BlackBox
@enduml
