@startuml
!include style.puml
skinparam Class {
    BorderColor BACKGROUND_COLOR
    FontColor BACKGROUND_COLOR
    BackgroundColor MODEL_COLOR_T2
    StereotypeFontColor BACKGROUND_COLOR
}
skinparam ArrowColor MODEL_COLOR_T2
Class HiddenOutside BACKGROUND_COLOR

Package Model <<Rectangle>> {
Class ReadOnlyXYZ <<Interface>>
Class Model <<Interface>>
Class ObservableList <<Interface>>
Class XYZManager
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
class HiddenClass

}

hide HiddenClass
hide member

Class HiddenOutside BACKGROUND_COLOR
HiddenOutside ..> Model

XYZManager .up.|> ReadOnlyXYZ

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o-down-> "6" XYZManager
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> HiddenClass
UserPrefs .up.|> ReadOnlyUserPrefs


@enduml
