@startuml
!include style.puml

skinparam Class {
    BorderColor BACKGROUND_COLOR
    FontColor BACKGROUND_COLOR
    BackgroundColor UI_COLOR_T3
    StereotypeFontColor BACKGROUND_COLOR
}
skinparam ArrowColor UI_COLOR_T3
Class HiddenOutside BACKGROUND_COLOR

hide member

package UI <<Rectangle>>{
Class Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class SideTabsBar
Class XYZTabPanel
Class XYZCard
Class DashboardPanel
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel BACKGROUND_COLOR
}

package Logic <<Rectangle>> {
Class HiddenLogic BACKGROUND_COLOR
}

Class HiddenOutside BACKGROUND_COLOR
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> SideTabsBar
MainWindow *-down-> XYZTabPanel
MainWindow *-down-> DashboardPanel

XYZTabPanel -down-> XYZCard

MainWindow -right-|> UiPart

ResultDisplay --|> UiPart
SideTabsBar -right-|> UiPart
CommandBox --|> UiPart
XYZTabPanel --|> UiPart
XYZCard --|> UiPart
DashboardPanel --|> UiPart
HelpWindow -down-|> UiPart

XYZCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

XYZTabPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- DashboardPanel

MainWindow -[hidden]-|> UiPart
@enduml
