= Charlotte Lim - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: EasyTravel
This portfolio aims to document the contributions that I have made to the *E.T.* project.
The Github Link to *E.T.* can be found here : https://github.com/AY1920S2-CS2103T-W17-3/main

== Overview
*E.T.* is a desktop travel planning application to provide a simple an easy way for users to prepare for their trip. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*:
Implemented Activity Tab along with its User Interface and commands (CRUD/Sort)

** What it does:
The activity manager feature allows the user to keep track of all the activities planned for their trip. It takes care of the title, duration and location of the activity. Users are also allowed to tag their activities with tags associated with them, such as expensive or sightseeing.

** Justification: This feature is essential when planning for a trip, as it allows the user to remember all of the activities planned so far.

** Highlights: The implementation too was challenging and time consuming as it required understanding existing commands within Address Book 3.

** Credits:
_{Authors or Address Book 3 and Jeffry Lum for his guidance, time and support. }_

* *Major enhancement*:
Implemented Trip commands (CRUD/Sort)

** What it does:
It allows the user to set a trip, edit a trip, as well as delete a trip.

** Justification: The trip manager feature is the core feature of Easy Travel. Without a trip, all the other features in Easy Travel will not be able to function.

** Highlights: The implementation was challenging and time consuming as features such as the Accommodation Bookings, the Schedule, the Transportation Bookings, and the Budget all depends on the Trip feature. Hence, I had to understand all the features to implement the Trip feature.

* *Minor enhancement*:
I did the base code for the progress check feature, so that my team members could work from there.

* *Minor enhancement*:
I implemented the dashboard UI for Easy Travel. It consists of the information of the trip set by the user, so that the user will have a visual of all the information of the trip at all times. The information consists of the trip's title, the start and end date of the trip, the budget set for the trip, as well as the exchange rate of the trip.

* *Code contributed*: [https://github.com/AY1920S2-CS2103T-W17-3/main/commits?author=Deunitato[All commits]] [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=deunitato[RepoSense Dashboard]]

* *Other contributions*:

** Project management:
*** There were a total of 4 releases, from version 1.1 to 1.4. I contributed to all the versions on GitHub.

** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage from 20% to 54% (Pull requests https://github.com/AY1920S2-CS2103T-W17-3/main/pull/356[#356], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/361[#361], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/379[#379] https://github.com/AY1920S2-CS2103T-W17-3/main/pull/388[#388])

** Documentation:
*** Used more 'you' language in the UserGuide so that it will be more reader-friendly. In addition, I added in pictures so that the reader can have visual cues on how the output should look like for each command.

** Team:
*** Bugs reported for E.T:
https://github.com/AY1920S2-CS2103T-W17-3/main/issues/158[#158], https://github.com/AY1920S2-CS2103T-W17-3/main/issues/335[#335], https://github.com/AY1920S2-CS2103T-W17-3/main/issues/336[#336],
*** Responsible for all non-official documentation such as weekly meeting minutes.

** Community:
*** PRs reviewed (with non-trivial review comments):
https://github.com/AY1920S2-CS2103T-W17-3/main/pulls?page=1&q=is%3Apr+is%3Aclosed+reviewed-by%3A%40me[PRs]
*** Reported bugs and suggestions for other teams in the class:
https://github.com/Deunitato/ped/issues[Bugs for Cooking Papa]


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=activity]

include::../UserGuide.adoc[tag=trip]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=tripmanagement]

include::../DeveloperGuide.adoc[tag=activitymanager]

