= Joshua Lay - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Easy Travel
This portfolio aims to document the contributions that I have made to the *E.T. Easy Travel* project.
The Github Link to *E.T. Easy travel* can be found here : https://github.com/AY1920S2-CS2103T-W17-3/main

== Overview
E.T. is a desktop travel planning application to provide a simple an easy way for users to prepare for their trip. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*:

Implemented Fixed Expense Tab along with its User Interface and commands (CRUD/Sort)

** What it does: Enable to user to add and subsequently modify their fixed expenses prior to the trip.

** Justification: This feature empowers the user to track their current expenses prior to their trip. By adding and subsequently modifying their expenses, the user would know how much of their
budget they have spent thus far, resolving the problem that our users, tend to overspend during their trip. Also, users are provided with an avenue to view their fixed expenses in a readable and organised manner.

** Highlights: The implementation too was challenging and time consuming as it required understanding existing commands within Address Book 3.
** Credits: _{Authors of Address Book 3 and Jeffry Lum for his guidance, time and support. }_

** *Minor Enhancement*: Created an interactive Pie Chart along with list for fixed expense.
*** What it does: Provides the user with a visual aid and breakdown of their current fixed expenses prior to the trip.
*** Justification: Allows users to determine which category of expenses they need to cut down if they are already over budget, or which categories they can spend more or less on.
*** Highlights: The implementation is time consuming as the documentation of javaFX was difficult to learn. Also the implementation the piechart was difficult in javaFX.

* *Code contributed*: [https://github.com/AY1920S2-CS2103T-W17-3/main/commits?author=joshlay96[All commits]] [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=joshlay96[RepoSense Dashboard]]

== Other contributions:

** Project management:
*** Set up Tasks for v1.1, closed v1.1 and v1.3 milestones.

** Enhancements to existing features:
*** Wrote tests for existing storage component as well as features to improve coverage [https://github.com/AY1920S2-CS2103T-W17-3/main/pull/362[#362]] [https://github.com/AY1920S2-CS2103T-W17-3/main/pull/364[#364]] [https://github.com/AY1920S2-CS2103T-W17-3/main/pull/374[#374]]
*** Fix Bugs present within our code. [https://github.com/AY1920S2-CS2103T-W17-3/main/pull/333[#333]] [https://github.com/AY1920S2-CS2103T-W17-3/main/pull/161[#161]] [https://github.com/AY1920S2-CS2103T-W17-3/main/pull/155[#155]]
*** Improved the Help Window. [https://github.com/AY1920S2-CS2103T-W17-3/main/pull/368[#368]]
*** Morph Address Book to Fixed Expense[https://github.com/AY1920S2-CS2103T-W17-3/main/pull/123[#123]] [https://github.com/AY1920S2-CS2103T-W17-3/main/pull/216[#216]]

** Documentation:
*** Contributed to the User and Developer Guides for this project. See below for more details.

** Community:
*** Provided insight on PRs made by my group (https://github.com/AY1920S2-CS2103T-W17-3/main/pulls?q=is%3Apr+commenter%3Ajoshlay96[PR Reviews])
*** Made a total of more than 30 PR's (https://github.com/AY1920S2-CS2103T-W17-3/main/pulls/@me[List of PR's])
*** Along with my group, provided DG comments for other groups (https://github.com/AY1920S2-CS2103-W14-3/main/issues/60[#1])

** Tools:
*** Integrated Travis CI in our code.

== Contributions to the User Guide
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=fixedexpense]

== Contributions to the Developer Guide

|===
|Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
include::../DeveloperGuide.adoc[tag=fixedexpense1]
include::../DeveloperGuide.adoc[tag=fixedexpense2]
include::../DeveloperGuide.adoc[tag=progresschecker]
include::../DeveloperGuide.adoc[tag=progresschecker1]

