= Joshua Wee - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Easy Travel

The purpose of this document is to document my contribution I have made to the project.

*_Easy Travel_* Github link: https://ay1920s2-cs2103t-w17-3.github.io/main/

== Overview

Easy Travel is a desktop travel planning application done by me and 4 other software engineering students for students who are planning for an overseas trip.

Easy Travel helps to reduce the amount of stress when planning for a trip by providing 5 main list: activity, transport booking, accommodation booking, packing list and fixed expense.

Easy Travel has a GUI created with JavaFX and user can interact with it through a CLI (Command Line Interface). It is written in Java and has about 10 kLoC

== Summary of contributions

* *Major enhancement*: Implemented Accommodation Booking Tab and commands

** What it does: The accommodation booking feature allows the user to keep track of all the accommodation bookings made before a trip. User can input details of the accommodation as well as the start and end day of the booking.

** Justification: This feature is useful in allowing users to keep track of the accommodations they have booked.

** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Minor enhancement*: Find overlaps in accommodation bookings

** What it does: Prevent users from entering multiple accommodation bookings that overlaps one another.

** Justification: To prevent users from booking overlapping accommodations or to prevent them from recording an accommodation that overlaps with other accommodations.

* *Minor enhancement*: Status check for missing accommodation days

** What it does: List down to the user the days that has missing accommodations.

** Justification: To give users an idea of the days that are missing accommodations so they can book it before going on the trip.

* *Code contributed*: [https://github.com/AY1920S2-CS2103T-W17-3/main/commits?author=jwee97[All commits]] [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=jwee97[Project Code Dashboard]]

* *Other contributions*:

** Enhancements to existing features:

*** Wrote test for existing feature to improve coverage

** Documentation:

*** Contributed to the User Guide and Developer Guide for this project. See below for more details.

** Community:

*** Over 30 https://github.com/AY1920S2-CS2103T-W17-3/main/pulls?q=is%3Apr+is%3Aclosed+author%3Ajwee97[Pull Requests] on Github

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=accommodation]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=accommodationbooking]
