= Catherine Loy - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Easy Travel
This portfolio aims to document the contributions that I have made to the *E.T.* project.
The Github Link to *E.T.* can be found here : https://github.com/AY1920S2-CS2103T-W17-3/main

== Overview
*E.T.* is a desktop travel planning application to provide a simple an easy way for users to prepare for their trip. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions
This section shows a summary of my coding, documentation, and other helpful contributions to the team project. It takes care of the name, quantity and categories of all the packing list items.

* *Major enhancement*:
Implemented Packing List Tab along with its User Interface and commands (CRUD/Sort)

** What it does:
The packing list feature allows the user to keep track of their packing list, to see which items they have and haven't packed for their trip.

** Justification:
When planning for a trip, it is important to have a packing list to keep track of what is packed and what needs to be packed, so that the traveller will not forget to bring anything they wanted to bring. This gives the traveller a peace of mind, convenience and preventing disasters, such as forgetting to bring one's passport or wallet.

** Highlights:
The implementation too was challenging and time consuming as it required understanding existing commands within Address Book 3.

** Credits:
Credits to the app called Packr for the packing list preset idea. +
_{Authors or Address Book 3 and Jeffry Lum for his guidance, time and support. }_

* *Major enhancement*:
I contributed to the most important feature of our product, the status feature. I added in the progress of the packing of the items, as well as the UI of this feature.

** What it does:
It checks the progress of planning that the user has done. It checks if firstly, there are no overlapping activities in the schedule, then it checks the number of packed items, then it checks if the total amount of the fixed expenses is under the budget, and lastly, it checks if there is an accommodation booking for every night of the trip.

** Justification:
The status feature ensures the user has planned for their trip fully before they embark on their trip. It prevents any slip-ups from the lack of planning, such as forgetting to pack something, to ensuring that they have a place to stay every night of their trip. This ensures that the trip is a smooth sailing one, with little slip-ups.

** Highlights:
The implementation was challenging and time consuming as it required understanding of all the other features, such as the
Accommodation Booking, the Schedule and the Budget.

* *Code contributed*: [https://github.com/AY1920S2-CS2103T-W17-3/main/commits?author=loycatherine[All commits]] [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=loycatherine[Project Code Dashboard]]

* *Other contributions*:

** Project management:
*** There were a total of 4 major releases, from version 1.1 to 1.4. I contributed to all the versions on GitHub.

** Enhancements to existing features:
*** Made the UI nicer by adding icons for all the features. (Pull requests https://github.com/AY1920S2-CS2103T-W17-3/main/pull/232[#232] https://github.com/AY1920S2-CS2103T-W17-3/main/pull/235[#235],  https://github.com/AY1920S2-CS2103T-W17-3/main/pull/239[#239], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/330[#330])
*** Wrote additional tests for existing features to improve coverage(Pull requests https://github.com/AY1920S2-CS2103T-W17-3/main/pull/143[#143] https://github.com/AY1920S2-CS2103T-W17-3/main/pull/359[#359] https://github.com/AY1920S2-CS2103T-W17-3/main/pull/366[#366])
*** Morph Address Book to Packing List (Pull request https://github.com/AY1920S2-CS2103T-W17-3/main/pull/122[#122])
*** Fix Bugs present within our code (Pull requests https://github.com/AY1920S2-CS2103T-W17-3/main/pull/245[#245], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/257[#257], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/349[#349], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/385[#385])

** Documentation:
*** Used more 'you' language in the UserGuide so that it will be more reader-friendly. In addition, I added in pictures so that the reader can have visual cues on how the output should look like for each command.

** Community:
*** Reviewed Pull Requests with non-trivial comments (Pull Requests https://github.com/AY1920S2-CS2103T-W17-3/main/pull/363[#363] https://github.com/AY1920S2-CS2103T-W17-3/main/pull/397[#397])
*** Reported bugs and offered suggestions for https://github.com/AY1920S2-CS2103T-W16-3/main[StudyBuddy], another AddressBook3-based application.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=packinglist]

include::../UserGuide.adoc[tag=v2.0]

include::../UserGuide.adoc[tag=packinglistcommands]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=listmanagement]

include::../DeveloperGuide.adoc[tag=packinglist]

include::../DeveloperGuide.adoc[tag=effort]

