= Chau Teng Le - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Easy Travel
https://github.com/AY1920S2-CS2103T-W17-3/main[GitHub]

== Overview
The purpose of this portfolio is to document my contributions to my software engineering team project. In this project, my team of five Computer Science students was tasked to enhance a basic command-line interface application (*AddressBook3*). We chose to transform it into our application called *E.T.*, which stands for *Easy Travel*. *E.T.* is an all-in-one travel planning application which helps travellers manage and plan for their overseas trips in various aspects.

This project portfolio will include a summary of my contributions followed by excerpts of the User Guide and Developer Guide that were written by me.

== Summary of contributions
The following enhancements were contributed by me.

[[major-1]]
=== Major enhancement 1 - Transport Booking Management
I added the *transport booking management* feature.

*What it does:* +
This feature provides basic functionalities for users to record and manage their transport bookings.

*Justification:* +
This feature covers transport booking management, which is an important aspect of overseas trip planning.

*Highlights:* +
This enhancement works well with the schedule feature (mentioned in <<major-2>>) as it helps users keep track of the program of their trip. Careful considerations have to be made so that this feature can be expanded upon by future developers, including myself. The implementation of this feature was challenging because certain restrictions must be enforced to ensure that the users' plans are appropriate.

[[major-2]]
=== Major enhancement 2 - Schedule
I provided a scheduling feature that helps users manage their programs for his/her trip.

*What it does:* +
This feature automatically adds transport bookings to the schedule. It also includes the `schedule` command which allows users to manually schedule activities at a particular time.

*Justification:* +
This is a necessary feature for a travel planning application as it is used for planning the trip itinerary. It also serves as a calendar to help users visualise their planned programs.

*Highlights:* +
This enhancement goes well with existing activity management features as well as transport booking management features (mentioned in <<major-1>>). However, the implementation of this feature was challenging because it integrates different features (namely activity and transport bookings). Additionally, an in-depth analysis of design options was needed to ensure that the implementation does not have unnecessary dependencies and can be extended in the future.

=== *Minor enhancement*:
I designed some aspects of the UI such that the side tab bar (Pull Request https://github.com/AY1920S2-CS2103T-W17-3/main/pull/218[#218]) and the application colour scheme (Pull Request https://github.com/AY1920S2-CS2103T-W17-3/main/pull/225[#225]).


=== *Code contributed*
- [https://github.com/AY1920S2-CS2103T-W17-3/main/commits?author=zenatrick[All commits]]
- [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#=undefined&search=zenatrick[Project Code Dashboard - RepoSense Report]]

=== *Other contributions*

* Project management:

** Managed 4 major https://github.com/AY1920S2-CS2103T-W17-3/main/releases[releases], from `v1.1` to `v1.4` on GitHub

* Enhancements to existing features:

** Involved in the morphing of the application from *AddressBook3* to *E.T.* (Pull Request https://github.com/AY1920S2-CS2103T-W17-3/main/pull/124[#124], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/132[#132])

** Fixed bugs reported by test users of the application (Pull Request https://github.com/AY1920S2-CS2103T-W17-3/main/pull/344[#344])

* Documentation:

** Help fix formatting errors and documentation bugs for the User Guide (Pull Request https://github.com/AY1920S2-CS2103T-W17-3/main/pull/396[#396]) and Developer Guide (Pull Request https://github.com/AY1920S2-CS2103T-W17-3/main/pull/384[#384])

* Community:

** Reviewed pull requests (with non-trivial comments)

*** Examples: Pull Requests https://github.com/AY1920S2-CS2103T-W17-3/main/pull/102[#102], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/125[#125], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/143[#143], https://github.com/AY1920S2-CS2103T-W17-3/main/pull/153[#153]

** Reported bugs for other teams

*** Examples: https://github.com/AY1920S2-CS2103T-W12-1/main/issues/285[1], https://github.com/AY1920S2-CS2103T-W12-1/main/issues/286[2], https://github.com/AY1920S2-CS2103T-W12-1/main/issues/287[3]

** Made documentation suggestions for other teams

*** Example: https://github.com/AY1920S2-CS2103-W15-3/main/issues/116[1]


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=schedule]

include::../UserGuide.adoc[tag=transport]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=scheduleactivity]

include::../DeveloperGuide.adoc[tag=transportbooking]
