@startuml

!include ../style.puml
title Finding an Activity

start

:Receives a ""findactivity"" command;

if () then ([valid command])

    if () then ([trip has been set])

            :Parses the
            ""findactivity"" command
            and the keywords;

            :Search for all activities
            with matching keywords;

            :Shows all the found
            activities to the user;

            :Shows a success message;

    else ([else])
            :Shows
            a trip-not-set
            error message;
    endif

else ([else])

    :Shows an
    invalid command
    error message;
endif

stop

@enduml
