@startuml
!include ../style.puml


Class Logic <<Interface>> {
+ execute() : CommandResult
}

Class LogicManager {
+ execute() : CommandResult
}

Class FixedExpense {
 - amount : Amount
 - description : Description
 - fixedExpenseCategory : FixedExpenseCategory
}



Class Model <<Interface>> {
+ addFixedExpense(FixedExpense)
+ getBudget() : Budget
+ setBudget(Budget)
+ getExchangeRate() :ExchangeRate
}

Class ModelManager{
+ addFixedExpense(FixedExpense)
+ getBudget() : Budget
+ setBudget(Budget)
+ getExchangeRate() :ExchangeRate
}

Class FixedExpenseManager{
+ addFixedExpense(FixedExpense)
}

Class TripManager{
+ getBudget() : Budget
+ setBudget(Budget)
+ getExchangeRate() :ExchangeRate
}

Class Trip{
- budget: Budget
- exchangeRate: ExchangeRate
+ getBudget() : Budget
+ setBudget(Budget)
+ getExchangeRate() :ExchangeRate
}
LogicManager .up-|> Logic
ModelManager .up-|> Model
ModelManager -down-> FixedExpenseManager
FixedExpenseManager --> " * "FixedExpense
LogicManager -left-> Model
ModelManager -right-> TripManager
TripManager --> "0..1  " Trip

show members
@enduml
