@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant "**:LogicManager**" as LogicManager LOGIC_COLOR
participant "**:EasyTravelParser**" as EtParser LOGIC_COLOR
participant "**:ScheduleActivityCommandParser**" as ScheduleActivityCommandParser LOGIC_COLOR
participant "**:ScheduleCommand**" as ScheduleCommand LOGIC_COLOR
end box

[-> LogicManager : execute("schedule 1 day/2 starttime/13:00")
activate LogicManager

LogicManager -> EtParser : parseCommand("schedule 1 day/2 starttime/13:00")
activate EtParser

create ScheduleActivityCommandParser
EtParser -> ScheduleActivityCommandParser
activate ScheduleActivityCommandParser

ScheduleActivityCommandParser --> EtParser
deactivate ScheduleActivityCommandParser

EtParser -> ScheduleActivityCommandParser : parse("1 day/2 starttime/13:00")
activate ScheduleActivityCommandParser

create ScheduleCommand
ScheduleActivityCommandParser -> ScheduleCommand
activate ScheduleCommand

ScheduleCommand --> ScheduleActivityCommandParser
deactivate ScheduleCommand

ScheduleActivityCommandParser --> EtParser
deactivate ScheduleActivityCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
ScheduleActivityCommandParser -[hidden]-> EtParser
destroy ScheduleActivityCommandParser

EtParser --> LogicManager
deactivate EtParser

LogicManager -> ScheduleCommand : execute()
activate ScheduleCommand

ref over ScheduleCommand : schedule activity

ScheduleCommand --> LogicManager : result
deactivate ScheduleCommand

[<--LogicManager
deactivate LogicManager
@enduml
