@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

interface ReadOnlyDaySchedule <<interface>>


Trip "1  "<.. TripManager
DaySchedule" *   " <.left. TripManager : contains <
ReadOnlyDaySchedule <|.. DaySchedule

class TripManager {
    - hasTrip:boolean
    - trip:Trip
    + hasTrip(): boolean
}

class Trip {
    - title:Title
    - startDate:Date
    - endDate:Date
    - numDays:int
    - budget:Budget
    - exchangeRate:ExchangeRate
}

show members

@enduml
