= E.T. V2.0 - User Guide
:site-section: UserGuide
:toc:
:toclevels: 5
:toc-title:
:toc-placement: preamble
:sectnums:
:sectnumlevels: 5
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S2-CS2103T-W17-3/main

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== *Introduction*

Welcome to the User Guide of **Easy Travel (E.T.)**!

Do you enjoy going on overseas trips, but dislike or have trouble planning for it? Fret not, our application, **E.T.**, will help reduce the amount of stress and anxiety when planning for a trip. **E.T.** is a desktop application that helps travellers **manage and plan for their trips**. This application uses a Command Line Interface (CLI); this means that you operate the application by typing commands into a Command Box. If you are fast at typing, you can manage your trips faster than other Graphical User Interface (GUI) applications; GUI applications allow users to interact with the application through graphical icons such as buttons.

The purpose of this user guide is to provide you with in-depth documentation on how to install and use our application. What are you waiting for? Head on to __Section 2 - Quick Start to get started.__

== *Quick Start*

To get started with using **E.T.**, you can follow these steps:

. Ensure that you have Java _11_ or above installed in your Computer. If you don’t you can install it using the link to Oracle https://www.oracle.com/java/technologies/javase-jdk11-downloads.html[here]
. Download the latest version of **E.T.** found https://github.com/AY1920S2-CS2103T-W17-3/main/releases[here].
. Copy the file to the folder you want to use as the home folder for **E.T.**.
. Double-click the file to start the app. The GUI shown in +++<u>Figure 1</u>+++ should appear in a few seconds.
. You are now on the main page of **E.T.**.
. At the bottom of the screen, type your command in the Command Box (label in +++<u>Figure 1</u>+++) and press <Enter> on your keyboard to execute it. E.g. typing `help` and pressing <Enter> will open the help window.

Refer to +++<u>Section 4.3 - Command Syntaxes and Usages</u>+++ on how to use commands and +++<u>Section 5 - Features</u>+++ on the commands you can use for each feature.


== *About*
=== Structure of this document
There are many things you can do with **E.T.**. Thus, we have structured this User Guide in such a way that you can easily find what you need. The next section, +++<u>Section 5 - Features</u>+++ will document the seven main features of **E.T.** and their commands:


[[Features]]
== *Features*
This section contains all the information you need to know about the features of E.T.. To use each feature or sub-feature, you will need to enter a command into the Command Box.


=== Trip Planner

The main feature of the app. Handles all trip and activity management.

==== Trip Management
This section contains the commands for the Trip Planner.

WARNING: A trip is required to be set before other features are unlocked

===== Create your brand new trip: `settrip`

Format: `settrip title/TITLE start/START_DATE end/END_DATE location/LOCATION budget/BUDGET exchangerate/EXCHANGERATE`

[IMPORTANT]
====
- There must not be a pre-existing trip set.
- Start and end dates must be a valid date.
- Title cannot exceed 50 characters.
- Budget must be a valid positive Integer from 0 to 1,000,000
- Exchange Rate must be a valid positive double from 0 to 100.
====

Let’s say you have an upcoming Graduation Trip and you are planning for it. You can execute a command as shown in the example below:

`settrip title/Graduation Trip start/28-09-2020 end/28-10-2020 location/Japan budget/5000 exchangerate/1.03`

This would create a trip titled “Graduation trip” with a start day of 28 September 2020 to 28 October 2020. The budget set is $5000 with the exchangerate of 1.03

After successfully setting a trip, you would see as shown in figure X below.

Figure 2: Message after successfully setting a trip.


===== Rename your trip: `rename`

Assume that you have accidentally titled the trip wrongly, you can execute the rename command to reverse any damages done as shown below


Format: `rename TITLE`

Example:

`rename Not a graduation trip.`

This changes the name of the trip to “Not a graduation trip” as shown in the figure below.

Expected output:
`Trip has been named: Not a graduation trip`

Figure 3: After renaming the trip


===== Editing your  trip’s budget: `editbudget`

Let’s say after planning your expenses, you realised that you would want to change the amount of money used for the trip. Using the editbudget command, you can edit the overall budget for your trip

Format: `editbudget AMOUNT`

[IMPORTANT]
====
- There must be a pre-existing trip set.
- The budget set must not be lesser than your total expenses.
====

For example, we want to decrease the budget for this trip from $5000 to $3000.

Example:

`Editbudget 3000`

E.T. will reflect the new budget in the trip info as shown in the figure below.

Figure 4: After editing budget to 3000

===== Delete your trip: `deletetrip`

Assuming that you have finished with your trip and would like to start planning for a new one, executing the deletetrip command would remove all traces of your previous trip and set a new clean space for you to start planning for the next one.

Format: `deletetrip`

Example:
`deletetrip`

Expected output:
`Trip has been deleted. All lists have been cleared!`

Deleting the trip would result in E.T. showing an empty screen as shown in figure 3. Execute the settrip to start another trip.


==== Scheduler (after opening a trip)

Allow users to manage the activities in the trip


===== View all your itinerary: `view`

Shows the entire itinerary

Format: `view`

Figure 6: After view command

===== Check how prepared you are: `status`

Assume you are not sure if you have already fully prepared for the trip, using the status command would confirm any fears and doubts about your preparation as well as warn you if you have any forgotten item that is not taken care of.

Using the status command would create a pop-up window as shown in figure 4.

Figure 7: The pop-up after using status command

[NOTE]
====
The pop-up would show you major warnings such as

- No expense/packing list item set
- Collisions in activities
- Over expenditure on budget
- Unchecked items in packing list
====

=== Activity Management
This section allows users to manage the activities in the trip.

==== Add your activity: `addactivity`
Lets say you wish to add in a new activity that you decided to do on the trip. Using the `addactivitiy` command would create and add your activity into the list.

Format: `addactivity title/TITLE duration/DURATION location/LOCATION [tag/tag]...`

Example:
`addactivity title/Going to the beach duration/4 location/Hakone tag/sea tag/ocean`

Figure 8: After add activity command

This would create and add an activity titled “Going to the beach" with a duration of 4 hours. The location of this activity is set to  “Hakone”, and has the tags “sea” and “ocean”.

==== Editing your activity: `editactivity`

Assume you have accidentally made a mistake in the spelling or the location of the activity and wish to change it. Running the `editactivity` command will allow you to make any changes to previously set activities.

Format: `editactivity INDEX [title/NAME][duration/DURATION][location/LOCATION][t/tag]...`

Example:
`editactivity 1 title/Go to an aquarium`

Figure 9: After edit activity command

In this example, this command will edit an existing activity at the index 1 ‘s title to “Go to an aquarium”. The other fields will stay the same.

IMPORTANT: The activity must exist to be edited

==== Deleting your activity: `deleteactivity`

Perhaps you decided that previously set activities are unviable and wish to remove it. Using the `deleteactivity` command would remove any activities that you do not want.

Format: `deleteactivity index`
Example:
`deleteactivity 1`

Figure 10: After delete activity command

In this example, you would delete an activity at the index 1

[IMPORTANT]
=====
The activity at that index must exist before deleting is allowed
=====

==== Clearing your planned activities: `clearactivity`

Perhaps you decided that all the activities you had planned before are not needed and want to start the activity list on a clean slate. Using the `clearactivity` command would clear any existing activities and replace your list with a brand new empty list.

Format: `clearactivity`

Example:
`clearactivity`

Figure 11: After clear activity command

[NOTE]
====
You can use this to delete all your activities at once
====

====  Find your activities
Let say you had added a bunch of activities and wished to search for a specific one. You can do it by using the find command to search through based on tags or by keyword.

`Findactivitytag` allows you to search by tags while `findactivity` command allows you to search by keyword.

Format: `findactivitytag tag`



Example:
`findactivitytag expensive`

This would show you the activities that have the tag expensive as shown in the figure 12.1.

Figure 12.1: After findactivitytag command

Let's say rather than finding by tags, you decided to search by keywords. You can use the `findactivity` to find base on the keywords you provided.

Format: `findactivity keyword`

Example:
`findactivity Osaka`

This would search for all activities with “Osaka” in it as shown in the figure 12.2

Figure 12.2: After findactivity command


=== Transportation Booking Management

The following sections [4.3.1 to 4.3.3] allows the user to manage transportation bookings for the trip.

==== Create new transportation booking: `addtransport`

If you have a new transportation booking, you can use this command to store the information and it will store the booking into a list.

Format: `addtransport mode/MODE startloc/START_LOCATION endloc/END_LOCATION starttime/DATE_TIME_OF_DEPARTURE endtime/DATE_TIME_OF_ARRIVAL`

[NOTE]
====
- `MODE` can be one of the following: `plane`, `bus`, `car`, `train`, `others`.
- `DATE_TIME_OF_DEPARTURE` and `DATE_TIME_OF_ARRIVAL` needs to be in the format `dd-MM-yyyy HH:mm`. `HH:mm` is the 24hr format time.
====

Examples:

`addtransport mode/plane startloc/Singapore endloc/Japan starttime/22-04-2021 09:00 endtime/22-04-2021 16:00`

If you have a plane booking, you can use `addtransport` to add the booking with the start location, end location, start time and end time.

==== Edit transportation booking: `edittransport`

If you have details for a given transport booking, you can use this command to edit certain details of the booking.

Format: `edittransport INDEX [mode/MODE] [startloc/START_LOCATION] [endloc/END_LOCATION] [starttime/DATE_TIME_OF_DEPARTURE] [endtime/DATE_TIME_OF_ARRIVAL]`

[NOTE]
====
- `INDEX` refers to the index number shown in the displayed transport booking list. `INDEX` *must be a positive integer* 1, 2, 3, ...
- At least one of the optional fields must be provided.
- Existing values will be updated to the input values.
- `MODE` can take one of the following values: `plane`, `bus`, `car`, `train`, `others`.
- `DATE_TIME_OF_DEPARTURE` and `DATE_TIME_OF_ARRIVAL` needs to be in the format `dd-MM-yyyy HH:mm`. `HH:mm` is the 24hr format time.
====

Examples:

`edittransport 2 starttime/22-04-2021 10:00`

In the case that the start time has changed to 22 April 2021 1000hr, you can use `editcommand` to change it.

`edittransport 4 mode/plane endloc/Italy`

In the case that you want to change the end location and mode of transport, you can use `editcommand` to change it.

==== Delete transportation booking: `deletetransport`

In the case that you want to remove the transport booking, you can use this command to remove it from the list.

Format: `deletetransport INDEX`

[NOTE]
`INDEX` refers to the index number shown in the displayed transport booking list. `INDEX` *must be a positive integer* 1, 2, 3, ...

Examples:

`deletetransport 1`

You can delete a transport booking by using the `deletetransport` command

==== Clear transportation booking: `cleartransport`

If you want to remove all the transportation bookings that you have made, this command will return an empty list for you to start working with again.

Format: `cleartransport`

[IMPORTANT]
This command will remove all the transportation booking that is in your current list

Example:

 cleartransport

You can use `cleartransport` to clear all transportation bookings in the list

=== Accommodation Booking

The following sections [4.4.1 to 4.4.3] allows the user to set and modify accommodation bookings in the trip.

===== Create a new accommodation booking: `addacc`

If you have made an accommodation booking, you can use this command to store it into a list and be able to keep track of it.

Format: `addacc name/NAME loc/LOCATION startday/START_DAY endday/END_DAY [remark/REMARK]`

[NOTE]
====
- `NAME` and `LOCATION` must be made of alphanumeric characters, and it must be less than 50 characters long
- `START_DAY` and `END_DAY` needs to be positive integers
- `START_DAY` refers to the day that you check in
- `END_DAY` refers to the day that you check out
- `REMARK` must be less than 150 characters long
====

Examples:

`addacc name/JW Marriott Hotel loc/KL startday/2 endday/4`

If you have a new accommodation booking for JW Marriott Hotel at KL on the 2nd day to the 4th day, you can create it using the `addacc` command

==== Edit accommodation booking: `editacc`

If you have to adjust the details of the accommodation booking and you wish to make changes, you can use this command to edit the necessary information.

Format: `editacc INDEX [name/NAME] [loc/LOCATION] [startday/START_DAY] [endday/END_DAY] [remark/REMARK]`

[NOTE]
====
- `INDEX` refers to the index number shown in the displayed transport booking list. `INDEX` *must be a positive integer* 1, 2, 3, ...
- `NAME` and `LOCATION` must be made of alphanumeric characters, and it must be less than 50 characters long
- `START_DAY` and `END_DAY` needs to be positive integers
- `START_DAY` refers to the day that you check in
- `END_DAY` refers to the day that you check out
- `REMARK` must be less than 150 characters long
====

Examples:

`edithotel 2 startday/4 endday/6`

In the case that you want to change the start day and end day of the 2nd accommodation, you can use `editacc` command.

`edithotel 3 address/Hilton KL remark/Check-in at 2pm`

You can also use this command to change the third accommodation booking in the list to Hilton, set the location to KL and change the remark to check in at 2pm.


==== Delete accommodation booking: `deletehotel`

Assuming you have another accommodation booking and plan to delete the previous one that you set on the same days, you can use this command to remove it.

Format: `deleteacc INDEX`

[NOTE]
`INDEX` refers to the index number shown in the displayed transport booking list. `INDEX` *must be a positive integer* 1, 2, 3, ...

Examples:

`deletehotel 2`

You can use `deleteacc` to delete the second accommodation booking.

==== Clear accommodation booking: `clearacc`

If you want to remove all the accommodation bookings that you have made, this command will return an empty list for you to start working with again.

Format: `clearacc`

[IMPORTANT]
This command will remove all the accommodation bookings that is in your current list

Example:

 clearacc

You can use `clearacc` to clear all accommodation bookings in the list


=== Packing List

Allow the user to have a packing list for the trip +
Format: `list`

The following sections [3.3.1. - 3.3.11] allows the user to set and modify the packing list for their trip.

===== Add a preset category: `addpreset`

Adds a preset category

Format: `addpreset preset/PRESET_NAME`

****
* Adds a preset category into the packing list.
* When a preset is selected, it will add a preset list of items under that category into that list.
****

Examples:

* `addpreset beach` +
Adds a preset list of items under beach into the packing list, such as sunblock, bathing suit, sunglasses, etc.

===== List all the presets in the packing list: `listpresets`

Lists all the presets in the packing list

Format: `listpresets`

****
* Lists all the presets in the packing list.
* The list will be shown in a pop up window.
****

Examples:

* `listpresets` +
Lists all the presets that one has currently, such as beach, camping, work, fancy dinner, etc.

===== Add an item in the packing list: `additem`

Creates an item in the packing list

Format: `additem item/ITEM quantity/QUANTITY`

****
* Adds an item into the packing list.
* If a duplicated item is added, it will let the user know that the item is already in the list.
* `QUANTITY` *must be a positive integer* 1,2,3...
****

Examples:

* `additem item/underwear quantity/5` +
Adds an item called underwear, with a quantity of 5

===== Edit an item in the packing list: `edititem`

Edits an item in the packing list

Format: `edititem INDEX [i/item] [q/quantity]`

****
* Edits an item in the packing list.
* Command can only be used if a budget has been added.
* Existing values will be updated to the input values.
* `quantity` *must be a positive integer* 1,2,3...
****

Examples:

* `edititem 1 item/boxer` +
Edits an item from index 1 to boxer
* `edititem 1 item/boxer quantity/3` +
Edits an item from index 1 to boxer, and edits the quantity from 5 to 3

===== Delete an item in the packing list: `deleteitem`

Deletes an item in the packing list

Format: `deleteitem INDEX`

****
* Deletes an item in the packing list.
* Command can only be used if an item has been added.
****

Examples:

* `deleteitem 1` +
Deletes item in the index 1 of the list

===== Mark an item as packed in the packing list: `checkitem`

Marks an item as packed in the packing list

Format: `checkitem INDEX`

****
* Checks an item off in the packing list.
* Command can only be used if an item has been added.
****

Examples:

* `checkitem 1` +
Marks item 1 in the packing list as packed

===== Mark an item as unpacked in the packing list: `uncheckitem`

Marks an item as packed in the packing list

Format: `uncheckitem INDEX`

****
* Unchecks an item off in the packing list.
* Command can only be used if an item has been added.
****

Examples:

* `uncheckitem 1` +
Marks item 1 in the packing list as unpacked

===== Sort items in the packing list: `sort`

Sorts items in the packing list

Format: `sort criteria/CRITERIA`

****
* Sorts items in the packing list according to a criteria.
* Command can only be used if at least 1 item has been added.
****

Examples:

* `sort alphabet` +
Sorts the packing list alphabetically

===== List the all sorting criteria for the packing list: `listcriteria`

Lists the all the possible sorting criteria for the packing list

Format: `listcriteria`

****
* Lists the all the possible sorting criteria for the packing list.
* The list will be shown in a pop up window.
****

Examples:

* `listcriteria` +
Lists all the possible criteria, such as alphabetically, by whether it is marked as packed, etc, in a pop up window

===== Save the current packing list as a preset: `savepreset`

Saves the current packing list as a preset

Format: `savepreset preset/PRESET_NAME`

****
* Saves the current packing list as a preset
* All items in the packing list when saved as a preset will be marked as not packed
* This is for future uses, if the user wants to use a previous trip's packing list again
****

Examples:

* `savepreset Japan 2020` +
Saves the current packing list as a preset called Japan 2020

===== Create a smart packing list: `createlist` [coming in v2.0]

Creates a smart packing list for inexperienced travelers

Format: `createlist days/DAYS [adult/ADULT] [children/CHILDREN] [season/SEASON]`

****
* Creates a list based on the information given by the user
* Useful for inexperienced users, as they do not know what to pack or the quantity to pack
* `DAYS`, `ADULT`, `CHILDREN`  *must be a positive integer* 1,2,3...
* `SEASON` *must be* Spring, Summer, Autumn, Winter
****

Examples:

* `createlist d/7, m/1, f/1, c/2, s/Summer` +
Creates a packing list based on the information provided. Since the trip is 7 days, with 1 male and 1 female,
7 sets of adult and child summer clothing will be packed, along with toys for the children.

===== Export the packing list as a txt file: `export` [coming in v2.0]

=== Fixed Expense Manager

Allow the user to set fixed expenses prior to the trip to allow users to plan a suitable budget for their upcoming trip.

Examples of Fixed Expenses include,
****
* Flight Tickets
* Hotel Accommodation Bookings
* Transportation Tickets
* Cost of admission tickets
* Or any other fixed miscellaneous costs
****

==== Modifying expenses

The following sections [3.4.4.1 - 3.4.4.4] allows a user to set and modify fixed expenses prior to the trip.

===== Adding a new fixed expense: `addexpense`

Allow the user to add a new expense.

Format: `addexpense amount/AMOUNT description/DESCRIPTION category/CATEGORY
[amountSGD/AMOUNT/SGD] [amountOTHR/AMOUNTOTHR]`

****
* Adds a new fixed expense for the upcoming trip.
* The amount *must be a positive integer*
* Both the `Description` and `Category` *must be alphanumeric word* and contains 50 and 30 characters respectively.
* At least one of the optional fields must be provided.
* If the user enters the expense in other currency, the amount will be automatically converted to SGD using the *exchange rate* provided.
****

Examples:

* `addexpense amount/1100 description/SQ Tickets category/Flights` +
Adds a fixed expense of $1100SGD, for `SQ Tickets` of category `Flights`.

* `addexpense amount/300 description/Bullet Train category/Transportation` +
Adds a fixed expense of $300SGD for `Bullet Train` of category `Transportation`.

===== Editing a fixed expense: `editexpense`

Allow the user to edit a fixed expense. The expense must have been already added to the fixed expense tracker.

Format: `editexpense INDEX amount/AMOUNT [description/DESCRIPTION] [category/CATEGORY] [amountSGD/AMOUNTSGD] [amountOTHR/AMOUNTOTHR]`

****
* Edits the expense at the specified `INDEX`. The index refers to the index number shown in the displayed fixed expense
list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* An *exchange rate* is required if the user is entering the amount in another currency.
* If the user enters the expense in other currency,
the amount will be automatically converted to SGD using the *exchange rate* provided.
****

Examples:

* `editexpense 1 amount/3000 description/Cathay Pacific Flight` +
Edit the details and amount paid in SGD of the 1st fixed expense to be `Cathay Pacific Flight` and `$3000 SGD` respectively.

* `editexpense 1 amountOTHR/3000 description/Business Class Flight category/Flight Ticket` +
Edit the details and amount paid in other currency of the 1st fixed expense to be
`Business Class Flight` and `$3000` respectively.
The amount will be automatically converted to SGD using *exchange rate* provided.

===== Deleting a fixed expense: `deleteexpense`

Allow the user to delete a fixed expense. The expense must be already added to the fixed expense list.

Format: `deleteexpense INDEX`

Examples:
* deleteexpense 1 +
Delete the 1st item in the fixed expense list.

===== Clearing a fixed expense: `clearexpense`

Allow the user to clear the fixed expense in the list.

Format: `clearexpense INDEX`

Example:
* clearexpense +
Clears the fixed expense in the list

==== Setting conversion rates: `conversion`

Allow the user to set conversion rates to allow for automatic conversion to SGD for any expenses incurred during the trip.

Format: `conversion rate/RATE`

****
* Sets a conversion rate from their currency to SGD.
* `RATE` must be a positive real number.
* Any expenses entered by the user during the trip would be automatically converted to SGD.
****


===== Sort fixed expenses according to amount spent: `sortexpense`

Allow the user to sort their fixed expense in the list.

Format: `sortexpense SORTIDENTIFIER [AMOUNT] [DESCRIPTION] [CATEGORY]`

****
* Sorts all fixed expense in ascending or descending order dependent on `SORTIDENTIFIER`.
* The list will be sorted in ascending order if `SORTIDENTIFIER` is 0 and descending order if `SORTIDENTIFIER` is 1.
* Only one of the optional fields [AMOUNT] [DESCRIPTION] [CATEGORY] must be provided and will sort the
list in ascending or descending order dependent on what needs to be sorted.
* The list must not be empty.
****

Examples:

* `sortexpense 1 amount` +
Sorts all fixed expense in descending order of amount.

* `sortexpense 0 description` +
Sorts all fixed expense in lexicographical order.


==== Recommend ways to save money based on prevailing usage [Coming in v2.0]

Use complex algorithms to monitor and track the user's spending habits. Recommend ways to save money on certain items.

==== Automatically keep track of expenses [Coming in v2.0]

Avoid requiring the user to enter their expenses on the application. Instead, all their expenses will be automatically entered into the app for them.

==== Export the diary to pdf file [Coming in V2.0]

=== Undo-Redo
Allows the user to revert their actions quickly and conveniently.

==== Undo an action: `undo`
Undo an undoable command entered by the user. +
Format: `undo`

Example:

* `undo`

==== Redo an action: `redo`
Redo an undone action after using the command `undo`. +
Format: `redo`

Example:

* `redo`

=== Auto-Complete [Coming in V2.0]

=== Import and export of data [Coming in V2.0]

== *FAQ*
*pass:[<u>TO BE EDITED</u>]*

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== *Command Summary*
*pass:[<u>TO BE EDITED</u>]*

* *Add* `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...` +
e.g. `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]...` +
e.g. `edit 2 n/James Lee e/jameslee@example.com`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find James Jake`
* *List* : `list`
* *Help* : `help`
