@startuml
title Sort Fixed Expense to Fixed Expense Manager

start

:User executes ""sortexpense"" command;
note left
  Arguments should contain
  an order and criteria
end note

if () then ([is a valid command])


    if () then ([no missing field])

            :Return a
            ""SortFixedExpenseCommand"" object;

            :Execute
            ""SortFixedExpenseCommand"";

            :Show sorted fixed expense
            list to the user;

    else ([missing field])
            : Throws an exception;

            : Show error message to the user;
    endif

else ([not a valid command])
    :Throw an exception;

    :Show error message to the user;
endif

stop

@enduml
