@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":**AddFixedExpenseCommand**" as AddFixedExpenseCommand LOGIC_COLOR
participant "**:CommandResult**" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "**toAdd:FixedExpense**" as FixedExpense MODEL_COLOR
participant "**:ModelManager**" as ModelManager MODEL_COLOR
participant "**:TripManager**" as TripManager MODEL_COLOR
participant "**FixedExpenseManager**" as FixedExpenseManager MODEL_COLOR



end box

[-> AddFixedExpenseCommand : execute()
activate AddFixedExpenseCommand

AddFixedExpenseCommand-> ModelManager : getExchangeRate()
activate ModelManager

ModelManager -> TripManager : getExchangeRate()
activate TripManager

TripManager --> ModelManager
deactivate TripManager

ModelManager --> AddFixedExpenseCommand
deactivate ModelManager

create FixedExpense
AddFixedExpenseCommand -> FixedExpense : new FixedExpense(amount, \nfixedExpenseCategory, description)
activate FixedExpense
note left: Parameters: Amount,\n FixedExpenseCategory, \nDescription

FixedExpense --> AddFixedExpenseCommand
deactivate FixedExpense

AddFixedExpenseCommand -> ModelManager : addFixedExpense()
activate ModelManager

ModelManager -> FixedExpenseManager : addFixedExpense()
activate FixedExpenseManager

FixedExpenseManager --> ModelManager
deactivate FixedExpenseManager

ModelManager --> AddFixedExpenseCommand
deactivate ModelManager



AddFixedExpenseCommand -> ModelManager : getTotalExpense()
activate ModelManager

ModelManager -> FixedExpenseManager : getTotalExpense()
activate FixedExpenseManager

FixedExpenseManager --> ModelManager
deactivate FixedExpenseManager

ModelManager --> AddFixedExpenseCommand
deactivate ModelManager


AddFixedExpenseCommand -> ModelManager : getBudget()
activate ModelManager

ModelManager -> TripManager :getBudget()
activate TripManager

TripManager --> ModelManager
deactivate TripManager

ModelManager --> AddFixedExpenseCommand
deactivate ModelManager


create CommandResult
AddFixedExpenseCommand -> CommandResult
activate CommandResult

CommandResult --> AddFixedExpenseCommand
deactivate CommandResult

[<-- AddFixedExpenseCommand : result
deactivate AddFixedExpenseCommand

@enduml
