@startuml
!include ../style.puml
skinparam backgroundColor #EEEBDC
skinparam arrowThickness 1.5
skinparam arrowColor MediumSpringGreen
skinparam classBackgroundColor MediumAquaMarine
skinparam classAttributeIconSize 0
skinparam classAttributeFontColor DarkSlateBlue

skinparam Class {
    FontColor MidnightBlue
    BorderThickness 1
    BorderColor MidnightBlue
    StereotypeFontColor #FFFFFF
    FontName Impact
}

Interface Logic <<Interface>> {
+ execute() : CommandResult
}

Class LogicManager {
+ execute() : CommandResult
}

Class FixedExpense {
 - amount : Amount
 - description : Description
 - fixedExpenseCategory : FixedExpenseCategory
 + getAmount() : Amount
 + getDescription() : Description
 + getFixedExpenseCategory() : FixedExpenseCategory
}



Interface Model <<Interface>> {
+ getBudget() : Budget
+ setBudget(Budget)
}

Class ModelManager{
+ setBudget(Budget)
+ getBudget() : Budget
}

Class FixedExpenseManager{
uniqueFixedExpensesLists : UniqueList<FixedExpenseManager>
+ addFixedExpense(FixedExpense)
+ getFixedExpenseList() : ObservableList<FixedExpense>
}

Class TripManager{
trip: Trip
+ getBudget() : Budget
+ setBudget(Budget)
}

Class Trip{
- budget: Budget
- exchangeRate: ExchangeRate
+ getBudget() : Budget
+ setBudget(Budget)
+ getExchangeRate() :ExchangeRate
}
LogicManager .up-|> Logic
ModelManager .up-|> Model
ModelManager -down-> FixedExpenseManager
FixedExpenseManager -right-> FixedExpense
LogicManager -down-> Model
ModelManager -right-> TripManager
TripManager -right-> Trip

show members
@enduml
