@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":**AddActivityCommand**" as AddActivityCommand LOGIC_COLOR
participant "**r:CommandResult**" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "**a:Activity**" as Activity MODEL_COLOR
participant "**m:ModelManager**" as ModelManager MODEL_COLOR
participant "**:ActivityManager**" as ActivityManager MODEL_COLOR

end box

[-> AddActivityCommand : ""execute(m)""
activate AddActivityCommand

AddActivityCommand -> ModelManager : ""hasTrip()""
activate ModelManager

ModelManager --> AddActivityCommand
deactivate

create Activity
AddActivityCommand -> Activity : ""new Activity(title, duration, ""\n""location, tags)""
activate Activity
note right
Parameter types of
""Activity"" constructor:
""Title"", ""Duration"",
""Location"", ""Tag""s (optional)
end note

Activity --> AddActivityCommand
deactivate Activity

AddActivityCommand -> ModelManager : ""addActivity(a)""
activate ModelManager

ModelManager -> ActivityManager : ""addActivity(a)""
activate ActivityManager

ActivityManager --> ModelManager
deactivate ActivityManager

ModelManager --> AddActivityCommand
deactivate ModelManager


create CommandResult
AddActivityCommand -> CommandResult
activate CommandResult

CommandResult --> AddActivityCommand : ""r""
deactivate CommandResult

[<-- AddActivityCommand : ""r""
deactivate AddActivityCommand

AddActivityCommand -[hidden]> CommandResult
destroy AddActivityCommand
@enduml

